### ISSUE TITLE
Curl commands don't copy over properly

### ISSUE THREAD

**Issue by stevengill** [adobe/stock-api-docs#29]
# Issue report

## URL where issue occurs
https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/01-getting-started.md but I've seen it happening in other places too such as https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/getting-started/03-api-authentication.md

## Type of issue
- [x] Other

## Brief description of issue
Using the copy button on https://www.adobe.io/apis/creativecloud/stock/docs.html#!adobe/stock-api-docs/master/docs/01-getting-started.md for the initial curl command doesn't work properly. The curl command has incorrect spacing to be pasted in the terminal and used. The spacing between the request url and `-H` header options is incorrect. This defeats the purpose of having a copy and paste initial workflow

## Proposed fix (if applicable)
I'd say it is worth it to properly format the the curl command (even though the UI of it being in one long line isn't ideal). Being able to quickly copy/paste the command is better than being able to see it fully on the page IMO. 

If you have a proposed solution, please submit a pull request! See the [contributing guidelines](CONTRIBUTING.md), and thanks for your contribution :)

**Comment by stevengill** [comment]
Filed a PR for it. Up to y'all to decide if it is worth it or not in terms of the ability to copy and paste vs UI of the command. https://github.com/adobe/stock-api-docs/pull/30

**Comment by chfabbro** [comment]
Thanks @stevengill! I was not aware there was a "Copy" button on the code blocks. That must have been a new (and unannounced) change to the implementation. The issue here is that this trades off functionality for legibility. As far as I can tell, if I do not insert newlines/returns into the code, it will display as a single line because I/O does not support code wrapping. I was thinking that since developers will realize the code cannot be used as-is (they must put in a valid API key), I assume they would know how to make the curl work properly. A separate issue is that the curl command is not compatible with Windows PowerShell, which is annoying but difficult to reconcile.
